
name: DEPLOY IOS
on:
  workflow_dispatch:
    inputs:
        isReleasing:
            description: '심사제출'
            type: boolean
            required: true
            default: true
        body:
            description: 'Version changes'
            required: false
            default: '수정사항'

concurrency:
  group: ${{ github.ref }}/ios/deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: macos-15
    env:
        PRODUCT_NAME: 'sendadv'
        IOS_CERT_PATH: 'cert.p12'
        IOS_PROFILE_PATH: 'profile.mobileprovision'
        IOS_KEY_PATH: 'api-key.json'
        GPG_PRIVATE_KEY_PATH: 'private.gpg'
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Import signing certificate
        env:
          IOS_CERT_BASE64: $IOS_CERT_PATH.base64
        run: |
          echo "${{ secrets.IOS_CERT_P12_DATA }}" > $IOS_CERT_BASE64
          base64 --decode -i $IOS_CERT_BASE64 -o $IOS_CERT_PATH

      - name: Import provisioning profile
        env:
          IOS_PROFILE_PATH_BASE64: $IOS_PROFILE_PATH.base64
        run: |
          echo "${{ secrets.IOS_PROFILE_DATA }}" > $IOS_PROFILE_PATH_BASE64
          base64 --decode -i $IOS_PROFILE_PATH_BASE64 -o $IOS_PROFILE_PATH

      - name: Remove Network Security Exceptions
        continue-on-error: true
        run: |
          /usr/libexec/PlistBuddy -c "delete :NSAppTransportSecurity:NSExceptionDomains" ./ios/$PRODUCT_NAME/Info.plist

      - name: Upgrade fastlane
        run: |
          sudo gem install fastlane

      - name: Export Fastlane App Store Key
        env:
          API_KEY_PATH_BASE64: $IOS_KEY_PATH.base64
        run: |
          echo '${{ secrets.IOS_API_KEY }}' > $API_KEY_PATH_BASE64
          base64 --decode -i $API_KEY_PATH_BASE64 -o $IOS_KEY_PATH
          rm $API_KEY_PATH_BASE64
          
      - name: Patch Xcode 15.3
        uses: 2sem/patch-package-resolved@v2
          
      - name: Build/Upload app
        env:
          PACKAGE_NAME: 'com.credif.sendadv'
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          IOS_CERT_PWD: '${{ secrets.IOS_CERT_P12_PWD }}'
          IOS_KEYCHAIN: ${{ secrets.IOS_KEYCHAIN }}
          IOS_KEYCHAIN_PWD: '${{ secrets.IOS_KEYCHAIN_PWD }}'
        run: |
          fastlane ios release description:'${{ github.event.inputs.body }}' isReleasing:${{ github.event.inputs.isReleasing }}
